
title: My Resume
url: 'https://isvogor-foi.github.io/'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Ivan Švogor
tagline: Software Engineering Postdoc
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: firstname.lastname(AT)foi.hr
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: isvogor
github: isvogor-foi
twitter: '@isvogor'

#Update all the sections by editing the files inside _includes folder.
